sudo: required

language: go

service:
  - docker

go:
  - 1.8.x
  - tip

install:
  - make install-tools

script:
  - make test-verify
  - make test-ut-test
  - make test-build
  - make deploy-dind-k8s
  - make test-e2e
  - make probe-test

