sudo: required

language: go

service:
  - docker

go:
  - 1.9.x
  - master

install:
  - make install-extra
  - go get github.com/mattn/goveralls

script:
  - make verify
  - make test-cover
  - make build

